# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: " " ## Should match to pApp parameter value
          ContainerPort: " " ## Should match to pAppPort parameter
Hooks:
  - AfterAllowTestTraffic: " "
